### ISSUE TITLE
Problema con instalacion limpia

### ISSUE THREAD

**Issue by Mxater** [LibreDTE/libredte-webapp#16]
Al generar una instalación nueva en Centos 7, con PHP 7.3 y Apache2, me genera el siguiente error al internar logearme

```
Warning: Class 'sowerphp\core\Model_Datasource_Database_PostgreSQL' not found in /usr/share/sowerphp/lib/sowerphp/core/App.php on line 134

Fatal error: Uncaught Error: Class '\Model_Datasource_Database_PostgreSQL' not found in /usr/share/sowerphp/lib/sowerphp/core/Model/Datasource/Database.php:59 Stack trace: #0 /usr/share/sowerphp/extensions/sowerphp/app/Model/Plural.php(90): sowerphp\core\Model_Datasource_Database::get('default') #1 /usr/share/sowerphp/extensions/sowerphp/app/Model/Plural.php(66): sowerphp\app\Model_Plural->getDB() #2 /usr/share/sowerphp/extensions/sowerphp/app/Controller/Component/Log.php(206): sowerphp\app\Model_Plural->__construct() #3 /usr/share/sowerphp/extensions/sowerphp/app/Controller/Component/Log.php(136): sowerphp\app\Controller_Component_Log->reportEmail(Array, 0, 3) #4 /usr/share/sowerphp/extensions/sowerphp/app/Controller/Component/Log.php(97): sowerphp\app\Controller_Component_Log->report(Array, Array) #5 [internal function]: sowerphp\app\Controller_Component_Log->afterFilter() #6 /usr/share/sowerphp/lib/sowerphp/core/Controller/Component/Collection.php(97): call_user_func_array(Array, Array) #7 /usr/share/sowerphp/lib/sower in /usr/share/sowerphp/lib/sowerphp/core/Model/Datasource/Database.php on line 59
```

Tengo instalado postgresql, la librería postgresql para PHP también.

**Comment by estebandelaf** [comment]
¿que versión exacta de PHP?

De todas formas, el soporte oficial es en Debian GNU/Linux 10, aunque probablemente sea algo de PHP.

**Comment by Mxater** [comment]
PHP 7.3.13 (cli) (built: Dec 17 2019 10:29:15) ( NTS )

esa es la versión

**Comment by estebandelaf** [comment]
En Debian 10 es la: PHP Version 7.3.11-1~deb10u1

No he probado en 7.3.13, menos en CentOS.

Si revisar la instalación y/o servidor no podría darte más ideas.

Recomiendo probar en el ambiente que está soportado oficialmente, Debian 10.
